# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create an autocart model
#'
#' @param response A vector of numeric response values with no NA entries.
#' @param data A dataframe for the predictor variables used in the autocart tree.
#' @param locations A two-column matrix with coordinates for the observations the predictor dataframe.
#' @param alpha A scalar value between 0 and 1 to weight autocorrelation against reduction in variance in the tree splitting. A value of 1 indicates full weighting on measures of autocorrelation.
#' @return An S3 object of class "autocart".
autocart <- function(response, data, locations, alpha) {
    .Call(`_autocart_autocart`, response, data, locations, alpha)
}

