# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create an autocart model
#'
#' @param response A vector of numeric response values with no NA entries.
#' @param data A dataframe for the predictor variables used in the autocart tree.
#' @param locations A two-column matrix with coordinates for the observations the predictor dataframe.
#' @param alpha A scalar value between 0 and 1 to weight autocorrelation against reduction in variance in the tree splitting. A value of 1 indicates full weighting on measures of autocorrelation.
#' @param beta A scalar value between 0 and 1 to weight the shape of the region in the splitting
#' @param control An object of type "autocartControl" returned by the \code{autocartControl} function to control the splitting in the autocart tree.
#' @return An S3 object of class "autocart".
#'
#' @import fields
#' @importFrom RcppParallel RcppParallelLibs
#' @export
autocart <- function(response, data, locations, alpha, beta, control = NULL) {
    .Call(`_autocart_autocart`, response, data, locations, alpha, beta, control)
}

#' Given an autocart model object, predict for new data passed in
#'
#' @param autocartModel An S3 object of type "autocart" returned from the autocart function
#' @param newdata A dataframe with the same amount of columns used to create the autocart model.
#' @return A numeric vector containing the predicted response value for each of the rows in the passed in dataframe.
#'
#' @export
predictAutocart <- function(autocartModel, newdata) {
    .Call(`_autocart_predictAutocart`, autocartModel, newdata)
}

