# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autocart_cpp <- function(response, data, locations, alpha, beta, control = NULL) {
    .Call(`_autocart_autocart_cpp`, response, data, locations, alpha, beta, control)
}

predictAutocart <- function(autocartModel, newdata) {
    .Call(`_autocart_predictAutocart`, autocartModel, newdata)
}

